version: '3.7'
services:
    postgres:
        image: postgres
        restart: unless-stopped
        env_file:
            - ../.env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
        networks:
          - ory
    kratos-migrate:
        depends_on:
            - postgres
        image: oryd/kratos:v0.11.1
        restart: on-failure
        command:
            migrate -c /etc/config/kratos/kratos.yml sql -e --yes
        volumes:
            -
                type: bind
                source: ./kratos
                target: /etc/config/kratos
        networks:
            - ory
    kratos:
        depends_on:
            - kratos-migrate
        image: oryd/kratos:v0.11.1
        restart: unless-stopped
        command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
        volumes:
            -
                type: bind
                source: ./kratos
                target: /etc/config/kratos
        env_file:
            - ../.env
        ports:
            - 4433:4433
            - 4434:4434
        networks:
            - ory
    kratos-import:
        depends_on:
            - kratos
        image: oryd/kratos:v0.11.1
        restart: "no"
        entrypoint: ["/bin/sh","-c"]
        command: 
            - |
              sleep 30
              kratos import identities /etc/config/kratos/admin.json
        volumes:
            -
                type: bind
                source: ./kratos
                target: /etc/config/kratos
        env_file:
            - ../.env
        networks:
            - ory
networks:
    ory:
