version: '3.7'
services:
    postgres:
        image: postgres
        restart: unless-stopped
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
        networks:
          - ory
    kratos-migrate:
        depends_on:
            - postgres
        image: bazel/ory/kratos:amazon_image
        restart: on-failure
        environment:
            DSN: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
        command:
            migrate -c kratos-production.yml sql -e --yes
        networks:
            - ory
    kratos:
        depends_on:
            - kratos-migrate
        image: bazel/ory/kratos:amazon_image
        restart: unless-stopped
        command: serve -c kratos-production.yml --dev --watch-courier
        ports:
            - 4433:4433
            - 4434:4434
        networks:
            - ory
    kratos-import:
        depends_on:
            - kratos
        image: bazel/ory/kratos:amazon_image
        restart: "no"
        entrypoint: ["/bin/sh","-c"]
        command: 
            - |
              sleep 30
              kratos import identities admin.json
        networks:
            - ory
networks:
    ory:
