cc_binary(
    name = "phtree_test",
    srcs = ["phtree_test.cc"],
    linkstatic = True,
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//filter_service/phtree",
    ],
)
